all:
  hosts:
    cisco_router:
      ansible_host: 192.168.1.1
      ansible_user: admin
      ansible_password: password
      ansible_network_os: cisco.ios.ios
      ansible_connection: network_cli
